server:
    host: 0.0.0.0
    port: 8080
    # When set to true, allows cookies to be sent over non-HTTPS connections.
    # WARNING: Only enable this in trusted environments like a homelab
    # where HTTPS is not available. This reduces security by allowing
    # cookies to be transmitted in plain text.
    allow_insecure_cookies: false
    # Enable native TLS. When true, application will run over HTTPS using the
    # supplied certificate and key paths.
    ssl: false
    ssl_cert:
    ssl_key:
wiki:
    root_dir: data
    documents_dir: documents
    title: "📚 Wiki-Go Demo"
    owner: wikigo.leomoon.com
    notice: Copyright 2025 © All rights reserved.
    timezone: America/Vancouver
    private: false
    disable_comments: false
    disable_file_upload_checking: false
    enable_link_embedding: false
    max_versions: 10
    # Maximum file upload size in MB
    max_upload_size: 1
    # Default language for the wiki interface (en, es, etc.)
    language: en
security:
    login_ban:
        # Enable protection against brute force login attacks
        enabled: true
        # Number of failed attempts before triggering a ban
        max_failures: 5
        # Time window in seconds for counting failures
        window_seconds: 180
        # Duration in seconds for the first ban
        initial_ban_seconds: 60
        # Maximum ban duration in seconds (24 hours)
        max_ban_seconds: 86400
users:
    - username: admin
      password: $2a$10$eJtF6/g7dpPtWv6QP9jmVuybt4uTFlb.r5Q2paCqmWHcl.W5DfSba
      role: admin